version: '3.1'
services:
  joomla:
    image: joomla
    restart: unless-stopped
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example  ## Hier Passwort eingeben ##
    volumes:
      - app:/var/www/htm
    ports:
      - 8080:80

  joomladb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example  ## Hier selbes Passwort eingeben ##
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  app:
