name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip -y
    
    - name: Package
      run: bash package.sh
    
    - name: Rename
      run: mv OpenJoomlaOAuth.zip OpenJoomlaOAuth-${{github.ref_name}}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: OpenJoomlaOAuth-${{github.ref_name}}.zip
